<h1>Quantas notas?<h1>
 <h3> Sistemas Lineares com Python<h3>
    
 



Um caixa automático de um banco só libera notas de 5 reais e 10 reais. Uma pessoa retirou desse caixa a importância de R$65,00 recebendo 10 notas. Quantas notas de cada valor o caixa liberou?

![image.png](atm.png "atm")

Sendo $x$ a quantidade de notas de 5 reais e $y$ a quantidade de notas de 10 reais, obtemos os sistema abaixo: \
   $\left\{\begin{array}{ccc}
    x+y&=&5 \\
    5x+10y&=&65
    \end{array}\right. $
    
Transformando em forma matricial temos: 

$\left[\begin{array}{cc}
    1&1 \\
    5&10
    \end{array}\right] $
 $\left[\begin{array}{c}
    x \\
    y
    \end{array}\right] $
    $=$
    $\left[\begin{array}{c}
    10 \\
    65
    \end{array}\right] $
   
Onde, \
$A=\left[\begin{array}{cc}
    1&1 \\
    5&10
    \end{array}\right] $,
$X=\left[\begin{array}{c}
    x \\
    y
    \end{array}\right] $
  e $B=\left[\begin{array}{c}
    10 \\
    65
    \end{array}\right] $ \ 
Assim temos que \
$AX=B \Rightarrow A^{-1}AX=A^{-1}B \Rightarrow X=A^{-1}B $ \

Calculando a matriz inversa de A, obtemos a matriz
$A^{-1}=\left[\begin{array}{cc}
  2&-\frac{1}{5} \\
  -1 & \frac{1}{5}
  \end{array}\right]$ 
  
  E por fim, multiplicando a matrizes A^{-1} e B, obtemos a matriz X:\
  $X=\left[\begin{array}{c}
  7 \\
  3
  \end{array}\right]$ \
  Disso concluímos que o caixa liberou 7 notas de 5 reais e 3 notas de 10 reais.  
  
  Agora vamos confererir as contas no Python:



In [16]:
import numpy as np

#declarar as matrizes
A = np.array([[1,1],[5,10]])
B = np.array([[10],[65]])

#encontrar a inversa da matriz A
A_inversa = np.linalg.inv(A)

#Encontrar X
X = np.dot(A_inversa,B)


In [17]:
A

array([[ 1,  1],
       [ 5, 10]])

In [18]:
B

array([[10],
       [65]])

In [19]:
X

array([[7.],
       [3.]])

Imagem retirada do site Flaticon. Disponível em: https://www.flaticon.com/free-icon/atm_2132773#term=cash%20machine&page=1&position=4